## Alt Küme Üzerinde İşlem Yapmak

In [2]:
import numpy as np

In [3]:
a = np.random.randint(10, size= (5,5))

In [4]:
a

array([[5, 6, 9, 8, 8],
       [9, 5, 6, 4, 3],
       [1, 9, 2, 9, 4],
       [0, 1, 9, 7, 6],
       [1, 9, 5, 9, 5]])

**Alt kümeleri genel kümeden bağımsız yapmak isteyebiliriz.**

In [7]:
alt_a = a[0:3,0:2]
alt_a

array([[5, 6],
       [9, 5],
       [1, 9]])

In [9]:
alt_a[0,0] = 9999
alt_a[1,1] = 8888

In [10]:
alt_a

array([[9999,    6],
       [   9, 8888],
       [   1,    9]])

In [12]:
a

array([[9999,    6,    9,    8,    8],
       [   9, 8888,    6,    4,    3],
       [   1,    9,    2,    9,    4],
       [   0,    1,    9,    7,    6],
       [   1,    9,    5,    9,    5]])

**Alt kümede yaptığımız değişiklikler ana kümede de meydana geldi.**

Şimdi de kopyalama işlemi yapalım.

In [15]:
m = np.random.randint(10, size = (5,5))
m

array([[0, 9, 4, 1, 7],
       [9, 1, 7, 8, 2],
       [3, 4, 0, 5, 2],
       [2, 9, 4, 4, 8],
       [4, 9, 1, 7, 5]])

In [16]:
alt_m = m[0:3, 0:2].copy()
alt_m


array([[0, 9],
       [9, 1],
       [3, 4]])

In [17]:
alt_m[0,0] = 9999
alt_m[1,1] = 8888

In [18]:
alt_m

array([[9999,    9],
       [   9, 8888],
       [   3,    4]])

In [19]:
m

array([[0, 9, 4, 1, 7],
       [9, 1, 7, 8, 2],
       [3, 4, 0, 5, 2],
       [2, 9, 4, 4, 8],
       [4, 9, 1, 7, 5]])

**Görüldüğü gibi copy() dediğimizde ana kümede değişiklik meydana gelmez.**