## Fancy Index ile Elemanlara Erişmek
İleri düzey eleman seçme imkanı vermektedir. Pandas'da da kullanılacaktır. **ÖNEMLİ!**

In [2]:
import numpy as np

In [5]:
a = np.arange(0,30,3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [7]:
a[1], a[0], a[5]

(3, 0, 15)

### Fancy Index Etkisi

In [9]:
al_getir = [1,0,5]
a[al_getir]

array([ 3,  0, 15])

In [12]:
m = np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
satir = np.array([0,1])
satir

array([0, 1])

In [15]:
sutun = np.array([1,2])
sutun

array([1, 2])

In [16]:
m[satir,sutun]

array([1, 5])

**Basit index ile fancy index**

In [18]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
m[0,[1,2]]

array([1, 2])

**Slice ile fancy index**

In [21]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])