In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
a>3

array([False, False, False,  True,  True])

In [5]:
a<3

array([ True,  True, False, False, False])

In [9]:
a<=3

True

In [10]:
a>=3

True

In [7]:
a==3

True

In [8]:
a!=3

False

## Matematik

In [11]:
a+5

8

In [12]:
a*5

15

In [13]:
a**2

9

In [14]:
a+25

28