## Matematiksel

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a-1

array([0, 1, 2, 3, 4])

In [4]:
a+1

array([2, 3, 4, 5, 6])

In [7]:
a*4

array([ 4,  8, 12, 16, 20])

In [8]:
a/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [9]:
a**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [10]:
a%2

array([1, 0, 1, 0, 1], dtype=int32)

### Ufunc

In [14]:
a

array([1, 2, 3, 4, 5])

In [18]:
np.subtract(a,1) #çıkartma

array([0, 1, 2, 3, 4])

In [19]:
np.add(a,1) #toplama

array([2, 3, 4, 5, 6])

In [20]:
np.multiply(a,4) #çarpma

array([ 4,  8, 12, 16, 20])

In [22]:
np.divide(a,5) #bölme

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [24]:
np.power(a,3) #kuvvet alma

array([  1,   8,  27,  64, 125], dtype=int32)

In [26]:
np.mod(a,2) #modunu alma

array([1, 0, 1, 0, 1], dtype=int32)

In [27]:
np.absolute(np.array([-5]))

array([5])

In [28]:
np.log(1)

0.0

In [33]:
np.log2(1)

0.0

In [34]:
np.log10(10)

1.0