In [1]:
# İlk önce kullanılacak kütüphaneleri import ediyoruz.

import numpy as np

In [3]:
# Tek boyutlu olanlar VEKTOR, iki boyutlu olanlar ise MATRIS'dir.

a = np.array([1,2,3,4,5])
b = np.array([2,3,4,5,6])
print(a*b)

[ 2  6 12 20 30]


Numpy arraylerini bu şekilde kolaylıkla çarpım işlemi yapabiliyoruz.

**Numpy Array'i Oluşturmak**

In [5]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


**Sıfırdan Array Oluşturmak**

In [6]:
a = np.zeros(10, dtype = "int")
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Birlerden Array Oluşturmak**

In [8]:
b = np.ones((3,5), dtype = "int")
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
c = np.full((2,10), 5)
c

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [10]:
np.arange(0,31,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [15]:
d = np.linspace(0,1,10)
print(d)
d.shape

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


(10,)

In [17]:
e = np.random.normal(10, 4, (3,4)) #Ortalaması 10, Standart Sapması 4 olan array.
e

array([[12.02142137,  3.19118906,  8.08850494,  1.59380824],
       [10.25245472, 12.42316982, 16.46464112,  9.64372105],
       [12.32161541,  5.50280529, 16.48433421, 12.81771027]])

In [18]:
f = np.random.randint(0,10, (3,3))
f

array([[8, 6, 6],
       [2, 7, 1],
       [8, 6, 5]])

### Özellikleri

* **ndim:** boyut sayısı
* **shape:** boyut bilgisi
* **size:** toplam eleman sayısı
* **dtype:** array veri tipi

In [20]:
g = np.random.randint(25, size = 5)

In [22]:
g

array([ 0,  3, 17, 18,  1])

In [24]:
g.ndim

1

In [25]:
g.shape

(5,)

In [26]:
g.size

5

In [27]:
g.dtype

dtype('int32')

In [28]:
h = np.random.randint(10, size = (3,5))

In [29]:
h.ndim

2

In [30]:
h.shape

(3, 5)

In [31]:
h.size

15

In [32]:
h.dtype

dtype('int32')