### Sıralama (sorting)

In [1]:
import numpy as np

In [2]:
a = np.array([2,5,3,4,1])

In [3]:
a

array([2, 5, 3, 4, 1])

In [5]:
np.sort(a) #veri setinin orijinal yapısını bozmaz.

array([1, 2, 3, 4, 5])

In [8]:
a.sort() #veri setinin yapısını bozar.

In [10]:
a #görüldüğü gibi bu şekilde yapısı değişir. 

array([1, 2, 3, 4, 5])

## İki boyutlu array sıralama

In [13]:
b = np.random.normal(20,3,(3,3))

In [14]:
b

array([[18.49281174, 20.90689573, 14.1889527 ],
       [23.08454937, 21.14159625, 14.59098331],
       [19.22758444, 22.81350169, 20.80734575]])

In [17]:
np.sort(b,axis=1) #satırları sıralar

array([[14.1889527 , 18.49281174, 20.90689573],
       [14.59098331, 21.14159625, 23.08454937],
       [19.22758444, 20.80734575, 22.81350169]])

In [18]:
np.sort(b,axis=0) #sütunları sıralar

array([[18.49281174, 20.90689573, 14.1889527 ],
       [19.22758444, 21.14159625, 14.59098331],
       [23.08454937, 22.81350169, 20.80734575]])