### Array Ayırma (splitting)

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,99,99,3,2,1])

In [3]:
a

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [4]:
np.split(a,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [5]:
a,b,c = np.split(a,[3,5])

In [6]:
a

array([1, 2, 3])

In [7]:
b

array([99, 99])

In [8]:
c

array([3, 2, 1])

## İki Boyutlu

In [16]:
m = np.arange(16).reshape(4,4)

In [17]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
ust, alt = np.vsplit(m,[2])

In [19]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
sol, sag = np.hsplit(m,[2])

In [24]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [23]:
sag

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])